"""Render a scorecard as a readable Markdown report with resolved citations."""

from .data import Evidence
from .schema import DimensionAssessment, ThesisScorecard

_RATING_BADGE = {
    "strong_positive": "🟢🟢 Strong Positive",
    "positive": "🟢 Positive",
    "neutral": "⚪ Neutral",
    "negative": "🔴 Negative",
    "strong_negative": "🔴🔴 Strong Negative",
    "insufficient_data": "⬜ Insufficient Data",
}


def _resolve(ids: list[str], by_id: dict[str, Evidence]) -> str:
    if not ids:
        return "_no citation_"
    parts = []
    for eid in ids:
        ev = by_id.get(eid)
        parts.append(f"`{eid}` {ev.label}" if ev else f"`{eid}`")
    return "; ".join(parts)


def _dimension_block(d: DimensionAssessment, by_id: dict[str, Evidence]) -> str:
    badge = _RATING_BADGE.get(d.rating.value, d.rating.value)
    return (
        f"### {d.dimension}\n"
        f"**{badge}**  ·  confidence: **{d.confidence.value}**\n\n"
        f"{d.rationale}\n\n"
        f"<sub>Evidence: {_resolve(d.evidence_ids, by_id)}</sub>\n"
    )


def render_markdown(card: ThesisScorecard, evidence: list[Evidence]) -> str:
    by_id = {e.id: e for e in evidence}
    overall = _RATING_BADGE.get(card.overall_rating.value, card.overall_rating.value)

    out = [
        f"# Thesis Scorecard — {card.company_name} ({card.ticker.upper()})",
        "",
        f"## Overall: {overall}  ·  confidence: **{card.overall_confidence.value}**",
        "",
        card.summary,
        "",
        "## Dimensions",
        "",
    ]
    out += [_dimension_block(d, by_id) for d in card.dimensions]

    out += ["## Key Risks", ""]
    out += [f"- {r}" for r in card.key_risks] or ["- _none stated_"]

    out += ["", "## Data Gaps (limit confidence)", ""]
    out += [f"- {g}" for g in card.data_gaps] or ["- _none stated_"]

    out += ["", "---", "", "## Evidence used", ""]
    out += [f"- `{e.id}` ({e.category}) **{e.label}**: {e.value}" for e in evidence]
    out += [
        "",
        "<sub>Generated by Equity Thesis Agent. Not investment advice. "
        "All ratings are grounded strictly in the evidence listed above.</sub>",
        "",
    ]
    return "\n".join(out)
